#!/usr/bin/env bash

set -a

[[ -f /etc/docker.env ]] && source /etc/docker.env

(systemctl is-active balena-registry \
  && curl -I --fail localhost) || exit $?

if [[ -s ${NODE_EXTRA_CA_CERTS} ]]; then
    true | openssl s_client \
      -connect haproxy:443 \
      -servername "${REGISTRY2_HOST}" \
      -CAfile "${NODE_EXTRA_CA_CERTS}"
else
    true | openssl s_client \
      -connect haproxy:443 \
      -servername "${REGISTRY2_HOST}"
fi
